# Base image
FROM ubuntu:22.04

# Set noninteractive mode
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Update and install tools
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    curl \
    wget \
    git \
    vim \
    htop \
    unzip \
    zip \
    tar \
    gnupg \
    ca-certificates \
    build-essential \
    software-properties-common \
    lsb-release \
    net-tools \
    iputils-ping \
    openssh-client \
    sudo \
    tmux \
    python3 \
    python3-pip \
    locales \
    fish \
    bash-completion \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set UTF-8 Locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Create a user
RUN useradd -ms /usr/bin/fish user && \
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Set default shell to fish
SHELL ["/usr/bin/fish", "-c"]

# Switch to user
USER user
WORKDIR /home/user

# Expose common dev ports :- SSH, HTTP, HTTPS, js, python, servers.
EXPOSE 22  80  443  3000  8000  8080  

# Default command
CMD ["fish"]
